[build]
  # Build command (if you have any build process, otherwise can be empty)
  command = "npm install"
  # Directory to publish (where your HTML file is located)
  publish = "."
  # Directory where your serverless functions are located
  functions = "netlify/functions"

[build.environment]
  # Environment variables for build process
  NODE_VERSION = "18"

# API routes for your backend functions
[[redirects]]
  from = "/api/ask/chatgpt"
  to = "/.netlify/functions/chat?model=chatgpt"
  status = 200
  method = "POST"

[[redirects]]
  from = "/api/ask/gemini"
  to = "/.netlify/functions/chat?model=gemini"
  status = 200
  method = "POST"

[[redirects]]
  from = "/api/ask/grok"
  to = "/.netlify/functions/chat?model=grok"
  status = 200
  method = "POST"

[[redirects]]
  from = "/api/ask/perplexity"
  to = "/.netlify/functions/chat?model=perplexity"
  status = 200
  method = "POST"

[[redirects]]
  from = "/api/ask/deepseek"
  to = "/.netlify/functions/chat?model=deepseek"
  status = 200
  method = "POST"

# Fallback for SPA routing (optional, for single page applications)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

# Function-specific settings
[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

# Environment variables (add your actual API key in Netlify dashboard)
[context.production.environment]
  OPENROUTER_API_KEY = "" # Add this in Netlify dashboard under Site settings > Environment variables

[context.deploy-preview.environment]
  OPENROUTER_API_KEY = "" # Same for deploy previews